import { Product } from '../context/ProductContext';

export const productsModel: Product[] = [
  {
    id: '1',
    title: 'Dell Inspiron 15',
    price: 2997.86,
    image: 'https://m.media-amazon.com/images/I/51lGW2nP9qL._AC_UL320_.jpg',
    description: 'Notebook potente com processador Intel i7 e 16 GB de RAM.',
    categoryId: '1',
  },
  {
    id: '2',
    title: 'Desktop HP Pavilion',
    price: 4200.00,
    image: 'https://m.media-amazon.com/images/I/71N5yYjl-ZL._AC_UL320_.jpg',
    description: 'Desktop robusto com armazenamento de 1 TB e 12 GB de RAM.',
    categoryId: '1',
  },
  {
    id: '3',
    title: 'MacBook Pro 13"',
    price: 8700.00,
    image: 'https://m.media-amazon.com/images/I/41J9j6iVDvS._AC_UL320_.jpg',
    description: 'MacBook Pro com chip M1 e 256 GB de SSD.',
    categoryId: '1',
  },
  {
    id: '4',
    title: 'Lenovo ThinkPad T470s',
    price: 3900.00,
    image: 'https://m.media-amazon.com/images/I/61HdBBQSDYL._AC_UL320_.jpg',
    description: 'ThinkPad durável com teclado ergonômico e 8 GB de RAM.',
    categoryId: '1',
  },
  {
    id: '5',
    title: 'iMac 24"',
    price: 12000.00,
    image: 'https://m.media-amazon.com/images/I/51hFDIZIdIL._AC_UL320_.jpg',
    description: 'iMac com tela Retina 4.5K e design ultrafino.',
    categoryId: '1',
  },
  {
    id: '6',
    title: 'iPhone 13 Pro',
    price: 9500.00,
    image: 'https://m.media-amazon.com/images/I/41X0xIWEpuL._AC_UL320_.jpg',
    description: 'iPhone 13 Pro com câmera tripla e 256 GB de armazenamento.',
    categoryId: '2',
  },
  {
    id: '7',
    title: 'Samsung Galaxy S21',
    price: 8000.00,
    image: 'https://m.media-amazon.com/images/I/61GrFSYnKVL._AC_UL320_.jpg',
    description: 'Galaxy S21 com tela AMOLED de 6.2" e 128 GB de armazenamento.',
    categoryId: '2',
  },
  {
    id: '8',
    title: 'iPad Air',
    price: 6000.00,
    image: 'https://m.media-amazon.com/images/I/511vXoVIcJL._AC_UL320_.jpg',
    description: 'iPad Air com chip A14 Bionic e tela de 10.9".',
    categoryId: '2',
  },
  {
    id: '9',
    title: 'Galaxy Tab S7',
    price: 5500.00,
    image: 'https://m.media-amazon.com/images/I/41zrg4ISTBL._AC_UL320_.jpg',
    description: 'Tablet Samsung Galaxy Tab S7 com S Pen e tela de 11".',
    categoryId: '2',
  },
  {
    id: '10',
    title: 'Xiaomi Mi 11',
    price: 4500.00,
    image: 'https://m.media-amazon.com/images/I/41GK+ItincL._AC_UL320_.jpg',
    description: 'Smartphone Xiaomi Mi 11 com câmera de 108 MP e 256 GB de armazenamento.',
    categoryId: '2',
  },
  {
    id: '11',
    title: 'Teclado Mecânico RGB',
    price: 350.00,
    image: 'https://m.media-amazon.com/images/I/61Tn5a431IL._AC_UL320_.jpg',
    description: 'Teclado mecânico com iluminação RGB personalizável.',
    categoryId: '3',
  },
  {
    id: '12',
    title: 'Mouse Logitech',
    price: 250.00,
    image: 'https://m.media-amazon.com/images/I/617w9nbQooL._AC_UL320_.jpg',
    description: 'Mouse gamer Logitech com sensor de alta precisão e botões programáveis.',
    categoryId: '3',
  },
  {
    id: '13',
    title: 'Monitor Ultrawide 34"',
    price: 2500.00,
    image: 'https://m.media-amazon.com/images/I/610YctsLfcL._AC_UL320_.jpg',
    description: 'Monitor ultrawide com resolução QHD e taxa de atualização de 144 Hz.',
    categoryId: '3',
  },
  {
    id: '14',
    title: 'Headset Bluetooth',
    price: 600.00,
    image: 'https://m.media-amazon.com/images/I/51InjrQDYpL._AC_UL320_.jpg',
    description: 'Headset Bluetooth com cancelamento de ruído e som de alta fidelidade.',
    categoryId: '4',
  },
  {
    id: '15',
    title: 'Som Bluetooth',
    price: 199.99,
    image: 'https://m.media-amazon.com/images/I/61mr8Fpv2TL._AC_UL320_.jpg',
    description: 'Caixa de som portátil com conexão Bluetooth, som estéreo de alta qualidade e bateria de longa duração.',
    categoryId: '4',
  },
  {
    id: '16',
    title: 'Fitness Amazfit Bip 6',
    price: 79.99,
    image: 'https://m.media-amazon.com/images/I/61ueYKWLNqL._AC_UL320_.jpg',
    description: 'Relógio inteligente com monitoramento de atividades físicas, frequência cardíaca e sono, com bateria de até 14 dias.',
    categoryId: '5',
  },
  {
    id: '17',
    title: 'Xiaomi Smart Band 8',
    price: 49.99,
    image: 'https://m.media-amazon.com/images/I/510YT6bvSiL._AC_UL320_.jpg',
    description: 'Pulseira inteligente com tela AMOLED de 1,62", monitoramento de atividades, frequência cardíaca e sono, resistente à água.',
    categoryId: '5',
  },
  {
    id: '18',
    title: 'Câmera Wi-Fi 2K',
    price: 39.99,
    image: 'https://m.media-amazon.com/images/I/51xgggjDFNL._AC_UL320_.jpg',
    description: 'Câmera de segurança com resolução 2K, visão noturna, detecção de movimento e áudio bidirecional, compatível com Alexa e Google Assistant.',
    categoryId: '5',
  },
  {
    id: '19',
    title: 'Smart TV 4K',
    price: 497.99,
    image: 'https://m.media-amazon.com/images/I/61vNhQJqHKL._AC_UL320_.jpg',
    description: 'Smart TV 4K UHD de 55" com tecnologia QLED, HDR, assistente de voz integrado e acesso a diversos aplicativos de streaming.',
    categoryId: '4',
  },
  {
    id: '20',
    title: 'Xbox Series X',
    price: 499.99,
    image: 'https://m.media-amazon.com/images/I/51bcwM0qLaL._AC_UL320_.jpg',
    description: 'Console de última geração com suporte a jogos em 4K, 1 TB de armazenamento e compatibilidade com milhares de jogos.',
    categoryId: '4',
  },
];



