import { Review } from '../context/ReviewContext';

export const reviewsModel: Review[] = [
  // Avaliações para Smartphones
  {
    id: '1',
    productId: '1',
    user: 'Alice',
    rating: 4.5,
    comment: 'Ótimo desempenho e câmera excelente!',
    date: '01/04/2025',
  },
  {
    id: '2',
    productId: '1',
    user: 'Bruno',
    rating: 4.0,
    comment: 'Bateria poderia durar mais, mas no geral é um bom aparelho.',
    date: '02/04/2025',
  },
  {
    id: '3',
    productId: '2',
    user: 'Carla',
    rating: 5.0,
    comment: 'Design incrível e muito rápido!',
    date: '03/04/2025',
  },
  {
    id: '4',
    productId: '2',
    user: 'Daniel',
    rating: 4.5,
    comment: 'Ótima relação custo-benefício.',
    date: '04/04/2025',
  },
  {
    id: '5',
    productId: '3',
    user: 'Eduarda',
    rating: 4.0,
    comment: 'Tela grande e cores vibrantes.',
    date: '05/04/2025',
  },
  {
    id: '6',
    productId: '3',
    user: 'Fernando',
    rating: 4.5,
    comment: 'Muito satisfeito com a compra.',
    date: '06/04/2025',
  },
  {
    id: '7',
    productId: '4',
    user: 'Gabriela',
    rating: 5.0,
    comment: 'Melhor smartphone que já tive!',
    date: '07/04/2025',
  },
  {
    id: '8',
    productId: '4',
    user: 'Henrique',
    rating: 4.5,
    comment: 'Funciona perfeitamente e é muito bonito.',
    date: '08/04/2025',
  },
  {
    id: '9',
    productId: '5',
    user: 'Isabela',
    rating: 4.0,
    comment: 'Atende bem às minhas necessidades diárias.',
    date: '09/04/2025',
  },
  {
    id: '10',
    productId: '5',
    user: 'João',
    rating: 4.5,
    comment: 'Bom custo-benefício.',
    date: '10/04/2025',
  },
  // Avaliações para Laptops
  {
    id: '11',
    productId: '6',
    user: 'Karla',
    rating: 5.0,
    comment: 'Performance excepcional para trabalho e jogos.',
    date: '11/04/2025',
  },
  {
    id: '12',
    productId: '6',
    user: 'Lucas',
    rating: 4.5,
    comment: 'Design elegante e bateria de longa duração.',
    date: '12/04/2025',
  },
  {
    id: '13',
    productId: '7',
    user: 'Mariana',
    rating: 4.0,
    comment: 'Leve e fácil de transportar.',
    date: '13/04/2025',
  },
  {
    id: '14',
    productId: '7',
    user: 'Nicolas',
    rating: 4.5,
    comment: 'Tela de alta resolução é um diferencial.',
    date: '14/04/2025',
  },
  {
    id: '15',
    productId: '8',
    user: 'Olivia',
    rating: 5.0,
    comment: 'Ótimo para edição de vídeos e fotos.',
    date: '15/04/2025',
  },
  {
    id: '16',
    productId: '8',
    user: 'Paulo',
    rating: 4.5,
    comment: 'Teclado confortável e touchpad responsivo.',
    date: '16/04/2025',
  },
  {
    id: '17',
    productId: '9',
    user: 'Quésia',
    rating: 4.0,
    comment: 'Boa capacidade de armazenamento.',
    date: '17/04/2025',
  },
  {
    id: '18',
    productId: '9',
    user: 'Rafael',
    rating: 4.5,
    comment: 'Processador rápido e eficiente.',
    date: '18/04/2025',
  },
  {
    id: '19',
    productId: '10',
    user: 'Sabrina',
    rating: 5.0,
    comment: 'Atendeu todas as minhas expectativas!',
    date: '19/04/2025',
  },
  {
    id: '20',
    productId: '10',
    user: 'Thiago',
    rating: 4.5,
    comment: 'Excelente custo-benefício.',
    date: '20/04/2025',
  },
  // Avaliações para Tablets
  {
    id: '21',
    productId: '11',
    user: 'Ursula',
    rating: 4.5,
    comment: 'Perfeito para leitura e navegação.',
    date: '21/04/2025',
  },
  {
    id: '22',
    productId: '11',
    user: 'Vinícius',
    rating: 4.0,
    comment: 'Boa duração de bateria.',
    date: '22/04/2025',
  },
  {
    id: '23',
    productId: '12',
    user: 'Wendy',
    rating: 5.0,
    comment: 'Ótimo para assistir filmes e séries.',
    date: '23/04/2025',
  },
  {
    id: '24',
    productId: '14',
    user: 'Carlos',
    rating: 4.0,
    comment: 'Ótima qualidade de som e conforto.',
    date: '22/03/2025',
  },
  {
    id: '25',
    productId: '14',
    user: 'Mariana',
    rating: 4.5,
    comment: 'Bateria dura bastante e é muito confortável.',
    date: '23/03/2025',
  },
  {
    id: '26',
    productId: '15',
    user: 'Roberto',
    rating: 5.0,
    comment: 'Monitor com cores vibrantes e alta resolução.',
    date: '24/03/2025',
  },
  {
    id: '27',
    productId: '15',
    user: 'Fernanda',
    rating: 4.5,
    comment: 'Design elegante e ótima qualidade de imagem.',
    date: '25/03/2025',
  },
  {
    id: '28',
    productId: '16',
    user: 'Lucas',
    rating: 4.0,
    comment: 'Teclado mecânico com ótima resposta tátil.',
    date: '26/03/2025',
  },
  {
    id: '29',
    productId: '16',
    user: 'Patrícia',
    rating: 4.5,
    comment: 'Iluminação RGB personalizável e confortável para digitar.',
    date: '27/03/2025',
  },
  {
    id: '30',
    productId: '17',
    user: 'André',
    rating: 5.0,
    comment: 'Mouse preciso e confortável para longas sessões de uso.',
    date: '28/03/2025',
  },
  {
    id: '31',
    productId: '17',
    user: 'Beatriz',
    rating: 4.5,
    comment: 'Design ergonômico e ótima sensibilidade.',
    date: '29/03/2025',
  },
  {
    id: '32',
    productId: '18',
    user: 'Eduardo',
    rating: 4.0,
    comment: 'Cadeira confortável e com ótimo suporte lombar.',
    date: '30/03/2025',
  },
  {
    id: '33',
    productId: '18',
    user: 'Vanessa',
    rating: 4.5,
    comment: 'Material de qualidade e fácil de montar.',
    date: '31/03/2025',
  },
  {
    id: '34',
    productId: '19',
    user: 'Ricardo',
    rating: 5.0,
    comment: 'Impressora rápida e com excelente qualidade de impressão.',
    date: '01/04/2025',
  },
  {
    id: '35',
    productId: '19',
    user: 'Sônia',
    rating: 4.5,
    comment: 'Fácil de configurar e usar.',
    date: '02/04/2025',
  },
  {
    id: '36',
    productId: '20',
    user: 'Marcelo',
    rating: 4.0,
    comment: 'Tablet com ótimo desempenho e tela de alta resolução.',
    date: '03/04/2025',
  },
  {
    id: '37',
    productId: '20',
    user: 'Aline',
    rating: 4.5,
    comment: 'Leve e com boa duração de bateria.',
    date: '04/04/2025',
  },
  {
    id: '38',
    productId: '21',
    user: 'Gustavo',
    rating: 5.0,
    comment: 'Smartwatch com muitas funcionalidades e design moderno.',
    date: '05/04/2025',
  },
  {
    id: '39',
    productId: '21',
    user: 'Camila',
    rating: 4.5,
    comment: 'Fácil de usar e sincronizar com o smartphone.',
    date: '06/04/2025',
  },
  {
    id: '40',
    productId: '22',
    user: 'Renato',
    rating: 4.0,
    comment: 'Câmera com ótima qualidade de imagem e fácil de transportar.',
    date: '07/04/2025',
  },
  {
    id: '41',
    productId: '22',
    user: 'Larissa',
    rating: 4.5,
    comment: 'Bateria dura bastante e possui muitos recursos.',
    date: '08/04/2025',
  },
  {
    id: '42',
    productId: '23',
    user: 'Fábio',
    rating: 5.0,
    comment: 'Console com gráficos incríveis e muitos jogos disponíveis.',
    date: '09/04/2025',
  },
  {
    id: '43',
    productId: '23',
    user: 'Juliana',
    rating: 4.5,
    comment: 'Interface amigável e ótimo desempenho.',
    date: '10/04/2025',
  },
  {
    id: '44',
    productId: '24',
    user: 'Otávio',
    rating: 4.0,
    comment: 'Sistema de som com qualidade excepcional e fácil de instalar.',
    date: '11/04/2025',
  },
  {
    id: '45',
    productId: '24',
    user: 'Isabela',
    rating: 4.5,
    comment: 'Design moderno e som potente.',
    date: '12/04/2025',
  },
];
